name: build-exe
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build executable
        run: pyinstaller --onefile --name WinKeyReader exe.py
      - name: Sign executable
        id: sign
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: ${{ secrets.CERTIFICATE }}
          password: ${{ secrets.CERTIFICATE_PASSWORD }}
          file: dist/WinKeyReader.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinKeyReader
          path: dist/WinKeyReader.exe
